package fr.aureliejosephine.mareu.services;

import java.util.List;

import fr.aureliejosephine.mareu.modele.Meeting;

public class MeetingServiceClass implements MeetingService {

    private List<Meeting> meetings = MeetingGenerator.generateMeetings();


    /**
     * Return a list of {@link Meeting}
     * Those users must be generated by {@link MeetingGenerator}
     */
    @Override
    public List<Meeting> getMeeting() {
        return meetings;
    }


    /**
     * Add a {@link Meeting} to the {@link MeetingServiceClass#meetings} list.
    */
    @Override
    public void addMeeting(Meeting meeting) {
        meetings.add(meeting);
    }


    /**
     * Delete a {@link Meeting} from the {@link MeetingServiceClass#meetings} list.
     */
    @Override
    public void deleteMeeting(Meeting meeting) {
        meetings.remove(meeting);
    }


}
